package model;

public enum ModeState {
    VERTEX_BUTTON_MODE, EDGE_BUTTON_MODE, DELETE_BUTTON_MODE, RENAME_BUTTON_MODE, FIND_PATH_MODE,
    FIND_SHORTEST_PATH_MODE, GET_DISTANCE_MODE, VERTEX_DEGREE_BUTTON;
}
